name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: sudo apt-get install -y iverilog

      - name: Check repo structure
        run: |
          for d in rtl tb formal scripts sw fpga docs; do
            if [ ! -d "$d" ]; then 
              echo "ERROR= $d missing dir"
              exit 1
            fi
          done
          echo ">>> [ci.yml]: Structure OK!"

      - name: Makefile exists
        run: test -f Makefile && echo ">>> [ci.yml]: Makefile OK!"

      - name: Sanity check RTL
        run: make sanity

        # --- TODO Stage 1 completion ---
  # sim_uart:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: sudo apt-get install -y iverilog
  #     - run: make sim_uart

        # --- TODO at Stage 4 ---
  # reggen:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: pip install pyyaml pandas matplotlib
  #     - run: make reggen

        # --- TODO at Stage 6 ---
  # regression:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: sudo apt-get install -y iverilog
  #     - run: pip install pyyaml pandas matplotlib
  #     - run: make regression
